jdk :
  - oraclejdk8
language : java
cache:
  directories:
  - $HOME/.m2
script : 
  - mvn clean test
  - mvn test -P IntegrationTests

before_install:
    - cp build/travis/travis-toolchains.xml ~/.m2/toolchains.xml

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_success:
  - cd modules/application
  - mvn org.eluder.coveralls:coveralls-maven-plugin:report
