jdk : oraclejdk8
language : java
cache:
  directories:
  - $HOME/.m2
script : mvn test
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_success:
  - mvn coveralls:report
