addons:
  sonarcloud:
    organization: "robward-scisys-github"
    token:
      secure: "$SONAR_TOKEN"

jdk :
  - oraclejdk8
language : java
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  
script : 
  - mvn clean test
  - mvn test -P IntegrationTests
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_success:
  - cd modules/application
  - mvn org.eluder.coveralls:coveralls-maven-plugin:report

